backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use common\models\LoginForm;
use yii\filters\VerbFilter;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use Yii;
use common\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\helpers\Url;
use yii\web\UploadedFile;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
	{
		$posts = \common\models\Post::find()
		->where(['status' => 1])
		->orderBy('id DESC')
		->all();
		
		$categories = \common\models\Category::find()
		->orderBy('name ASC')
		->all();
		
		return $this->render('index', [
			'posts' => $posts,
			'categories' => $categories,
		]);
	}

    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return mixed
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail(Yii::$app->params['adminEmail'])) {
                Yii::$app->session->setFlash('success', 'Thank you for contacting us. We will respond to you as soon as possible.');
            } else {
                Yii::$app->session->setFlash('error', 'There was an error sending email.');
            }

            return $this->refresh();
        } else {
            return $this->render('contact', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Displays about page.
     *
     * @return mixed
     */
    public function actionAbout()
    {
        return $this->render('about');
    }

    /**
     * Signs user up.
     *
     * @return mixed
     */
    public function actionSignup()
    {
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                if (Yii::$app->getUser()->login($user)) {
                    return $this->goHome();
                }
            }
        }

        return $this->render('signup', [
            'model' => $model,
        ]);
    }

    /**
     * Requests password reset.
     *
     * @return mixed
     */
    public function actionRequestPasswordReset()
    {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Check your email for further instructions.');

                return $this->goHome();
            } else {
                Yii::$app->session->setFlash('error', 'Sorry, we are unable to reset password for email provided.');
            }
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    /**
     * Resets password.
     *
     * @param string $token
     * @return mixed
     * @throws BadRequestHttpException
     */
    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->session->setFlash('success', 'New password was saved.');

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }
	
	public function actionDetails($id)
	{
		$post = \common\models\Post::find()
		->where(['status' => 1, 'id' => $id])
		->one();
	
		$categories = \common\models\Category::find()
		->orderBy('name ASC')
		->all();
		
		$comments = \common\models\Comment::find()
        ->where(['status' => 1,'post_id'=>$id])
        ->orderBy('id DESC')
        ->all();
		
		$model = new \common\models\Comment();
		
		if ($model->load(Yii::$app->request->post())) 
		{
			$model->post_id=$id;
			$model->created_at=time();

			if (!Yii::$app->user->isGuest)
			{
				$model->user_id=Yii::$app->user->identity->id;
				$model->email=Yii::$app->user->identity->email;
				$model->status=1;
			}
			
			if ($model->validate()) 
			{
				if($model->save())
				{
					Yii::$app->session->setFlash('success', 'Comment was saved.');
					return $this->redirect(Url::current(),302);
				}
			}	
		}
	
		return $this->render('details', [
			'post' => $post,
			'categories' => $categories,
			'comments' => $comments,
			'model' => $model,
		]);
	}
	
	public function actionCategoryList($id)
	{
		$posts = \common\models\Post::find()
        ->where(['status' => 1,'category_id'=>$id])
        ->orderBy('id DESC')
        ->all();
		
		$categories = \common\models\Category::find()
		->orderBy('name ASC')
		->all();
		
		$cat_name = \common\models\Category::find()
		->where(['id'=>$id])
		->one();
		
		return $this->render('categoryList', [
			'categories' => $categories,
			'posts' => $posts,
			'cat_name' => $cat_name['name'],
		]);
	}
	
	public function actionNewTopic($id = null)
	{
		$time = time();
		$categories = \common\models\Category::find()
		->orderBy('name ASC')
		->all();
		
		if($id == null)
		{
			$model = new \common\models\Post();
			$model->created_at=$time;
		}
		else
		{
			$model = \common\models\Post::find()->where(['id' => $id])->one();;
			$model->updated_at=$time;
			$img = $model->image;
		}
		
		if ($model->load(Yii::$app->request->post())) 
		{
			$file = UploadedFile::getInstance($model, 'image');
			if($file && $file->getExtension() != 'jpg')
			{
				Yii::$app->session->setFlash('error', 'Error, Please upload jpg image only');
				return $this->redirect(Url::current(),302);
			}
			if($file)
			{
				$model->image = $time.$file->name;
			}
			else
			{
				if($id != null)
				{
					$model->image = $img;
				}
			}
	
			$model->user_id=Yii::$app->user->identity->id;
			$model->status=1;

			if ($model->validate()) 
			{
				if($model->save())
				{
					if($file)
					{
						 $file->saveAs('images/'.$time.$file->name);
					}
					Yii::$app->session->setFlash('success', 'Article was saved,');
					return $this->redirect(Url::current(['id'=>$model->id]),302);
				}
			}
		}
		
		return $this->render('newTopicForm', [
			'categories' => $categories,
			'model' => $model,
		]);
	}
}

frontend/views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>This is the About page. You may modify the following file to customize its content:</p>

    <code><?= __FILE__ ?></code>
</div>

frontend/views/site/categoryList.php
<?php
use yii\bootstrap\Nav;
use yii\helpers\Html;

$this->title = 'Category: '.$cat_name;
/* @var $this yii\web\View */

?>

<?php
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="site-index">
<!--
    <div>
        <h1>Congratulations!</h1>

        <p class="lead">You have successfully created your Yii-powered application.</p>

        <p><a class="btn btn-lg btn-success" href="http://www.yiiframework.com">Get started with Yii</a></p>
    </div>
-->
    <div class="body-content">

        <div class="row">
			<div class="col-lg-9">
				<?php				
				foreach($posts as $post){
					echo '<div>';
					echo '<a href="'.\Yii::$app->urlManager->createUrl(['site/details', 'id' => $post->id]).'"><h2>'.$post->title.'</h2></a>';
					echo '<p>'.substr($post->content,0,300).'... <a href="'.\Yii::$app->urlManager->createUrl(['site/details', 'id' => $post->id]).'">readmore &raquo;</a></p>';
					if($post->image)
					{
						echo '<img src="images/'.$post->image.'" height="200">';
					}
					echo '<p><small>Posted by '.$post->user->username.' at '.date('F j, Y, g:i a',$post->created_at).'</small></p>';
					echo '</div>';
				}
				?>                
            </div>
            <div class="col-lg-3">
                <h2>Category</h2>
				<?php				
				$items=[];	
				foreach($categories as $category){
					$items[]=['label' => $category->name , 'url' => \Yii::$app->urlManager->createUrl(['site/category-list', 'id' => $category->id])];
				}
				echo Nav::widget([
					'items' => $items,
				]);
				?>                
            </div>
        </div>

    </div>
</div>

frontend/views/site/commentForm.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\Comment */
/* @var $form ActiveForm */
?>
<div class="site-commentForm">

    <?php $form = ActiveForm::begin(); ?>

        <?= $form->field($model, 'email')->textinput(['style'=>'width:20%;']) ?>
        <?= $form->field($model, 'url')->textinput(['style'=>'width:50%;']) ?>
		<?= $form->field($model, 'content')->textarea(['rows'=>3]) ?>
    
        <div class="form-group">
			<?php
			if (!Yii::$app->user->isGuest)
			{
				echo Html::submitButton('Say It!', ['class' => 'btn btn-primary']);
			}
			else
			{
				echo Html::submitButton('Please Login to Comment', ['class' => 'btn btn-primary', 'disabled'=>true]);
			}
			?>
        </div>
    <?php ActiveForm::end(); ?>

</div><!-- site-commentForm -->

frontend/views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.
    </p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                <?= $form->field($model, 'name') ?>

                <?= $form->field($model, 'email') ?>

                <?= $form->field($model, 'subject') ?>

                <?= $form->field($model, 'body')->textArea(['rows' => 6]) ?>

                <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                    'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                ]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>

</div>

frontend/views/site/details.php
<?php
use yii\bootstrap\Nav;
use yii\helper\HTML;

$this->title = $post->title;
/* @var $this yii\web\View */


?>

<?php
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="site-index">
<!--
    <div>
        <h1>Congratulations!</h1>

        <p class="lead">You have successfully created your Yii-powered application.</p>

        <p><a class="btn btn-lg btn-success" href="http://www.yiiframework.com">Get started with Yii</a></p>
    </div>
-->
    <div class="body-content">

        <div class="row">
			<div class="col-lg-9">
				<?php				
				// foreach($post as $post){
					echo '<div>';
					echo '<h2>'.$post->title.'</h2>';
					echo '<p><small>Posted by '.$post->user->username.' at '.date('F j, Y, g:i a',$post->created_at).'</small></p>';
					if($post->image)
					{
						echo '<img src="images/'.$post->image.'" height="420">' ;
					}
					echo '<p>'.$post->content.'</p>';
					// echo '<p><a class="btn btn-default" href="'.\Yii::$app->urlManager->createUrl(['site/details', 'id' => $post->id]).'">readmore &raquo;</a></p>';
					echo '</div>';
				// }
				
				echo '<br><h4>Comment <span class="glyphicon glyphicon-comment"></span></h4>';
				
				foreach($comments as $comment)
				{
					echo "<div style='border-bottom:1px solid #ddd; padding:5px;margin:5px;'>";
					echo "<p><small>
					  Comment by ".$comment->user->username." at ".date("F j, Y, g:i a",$comment->created_at).
					  "</small></p>";
					echo $comment->content;
					echo "</div>";
				}
				
				if(empty($comments))
				{
					echo "<div padding:5px;margin:5px;'>";
					echo 'No Comment In This Article Yet!';
					echo "</div>";
				}
				
				echo '<div class="clearfix"></div><br>';
				
				echo $this->render('commentForm', [
					'model' => $model,
				]);
				?>                
            </div>
            <div class="col-lg-3">
                <h2>Category</h2>
				<?php				
				$items=[];	
				foreach($categories as $category){
					$items[]=['label' => $category->name , 'url' => \Yii::$app->urlManager->createUrl(['site/category-list', 'id' => $category->id])];
				}
				echo Nav::widget([
					'items' => $items,
				]);
				?>                
            </div>
        </div>

    </div>
</div>

frontend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

frontend/views/site/index.php
<?php
use yii\bootstrap\Nav;
$this->title = 'Online Game Portal';
/* @var $this yii\web\View */

?>
<div class="site-index">

<?php 
if (!Yii::$app->user->isGuest)
{
?>
    <div>
        <p><a class="btn btn-lg btn-success" href="<?php echo \Yii::$app->urlManager->createUrl(['site/new-topic']) ?>"><span class="glyphicon glyphicon-file"></span> New &raquo;</a></p>
    </div>
<?php
}
?>

    <div class="body-content">

        <div class="row">
			<div class="col-lg-9">
				<?php				
				foreach($posts as $post){
					echo '<div>';
					echo '<a href="'.\Yii::$app->urlManager->createUrl(['site/details', 'id' => $post->id]).'"><h2>'.$post->title.'</h2></a>';
					echo '<p>'.substr($post->content,0,300).'... <a href="'.\Yii::$app->urlManager->createUrl(['site/details', 'id' => $post->id]).'">readmore &raquo;</a></p>';
					
					if($post->image)
					{
						echo '<img src="images/'.$post->image.'" height="200">';
					}
					echo '<p>';
					echo '<p><small>Posted by '.$post->user->username.' at '.date('F j, Y, g:i a',$post->created_at).'</small></p>';
										
					if (!Yii::$app->user->isGuest)
					{
						if(Yii::$app->user->identity->id === $post->user_id)
						{
							echo '<a class="btn btn-default" href="'.\Yii::$app->urlManager->createUrl(['site/new-topic', 'id' => $post->id]).'"><span class="glyphicon glyphicon-edit"></span> Edit &raquo;</a>';
						}
					}
					
					echo '</p>';
					echo '</div>';
				}
				?>                
            </div>
            <div class="col-lg-3">
                <h2>Category</h2>
				<?php				
				$items=[];	
				foreach($categories as $category){
					$items[]=['label' => $category->name , 'url' => \Yii::$app->urlManager->createUrl(['site/category-list', 'id' => $category->id])];
				}
				echo Nav::widget([
					'items' => $items,
				]);
				?>                
            </div>
        </div>

    </div>
</div>

frontend/views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'login-form']); ?>

                <?= $form->field($model, 'username') ?>

                <?= $form->field($model, 'password')->passwordInput() ?>

                <?= $form->field($model, 'rememberMe')->checkbox() ?>

                <div style="color:#999;margin:1em 0">
                    If you forgot your password you can <?= Html::a('reset it', ['site/request-password-reset']) ?>.
                </div>

                <div class="form-group">
                    <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/newTopicForm.php
<?php

use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use dosamigos\tinymce\TinyMce;

$this->title = 'Create/Edit';
/* @var $this yii\web\View */
/* @var $model common\models\Post */
/* @var $form ActiveForm */
?>
<h1><?= Html::encode($this->title) ?></h1>
<?php
$this->params['breadcrumbs'][] = $this->title;
?>
<p>Please fill out the form</p>

<div class="site-newTopicForm">
	
    <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]); ?>

        <?= $form->field($model, 'category_id')->dropDownList(
            ArrayHelper::map($categories, 'id', 'name')
            ) ?>
        <?= $form->field($model, 'title') ?>
        <?= $form->field($model, 'content')->widget(TinyMce::className(), [
    'options' => ['rows' => 6],
    'language' => 'en_GB',
    'clientOptions' => [
        'plugins' => [
            "advlist autolink lists link charmap print preview anchor",
            "searchreplace visualblocks code fullscreen",
            "insertdatetime media table contextmenu paste"
        ],
        'toolbar' => "undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image"
    ]
]) ?>
        <?php
		if($model->image)
		{
			echo '<img src="images/'.$model->image.'" height="320">'; 
		}
		?>
		<?= $form->field($model, 'image')->fileInput() ?>

    
        <div class="form-group">
            <?= Html::submitButton('Submit', ['class' => 'btn btn-primary']) ?>
        </div>
    <?php ActiveForm::end(); ?>

</div><!-- site-newTopicForm -->

frontend/views/site/requestPasswordResetToken.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\PasswordResetRequestForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Request password reset';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-request-password-reset">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out your email. A link to reset password will be sent there.</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'request-password-reset-form']); ?>

                <?= $form->field($model, 'email') ?>

                <div class="form-group">
                    <?= Html::submitButton('Send', ['class' => 'btn btn-primary']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/resetPassword.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ResetPasswordForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Reset password';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-reset-password">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please choose your new password:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'reset-password-form']); ?>

                <?= $form->field($model, 'password')->passwordInput() ?>

                <div class="form-group">
                    <?= Html::submitButton('Save', ['class' => 'btn btn-primary']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/signup.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\SignupForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Signup';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-signup">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to signup:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'form-signup']); ?>

                <?= $form->field($model, 'username') ?>

                <?= $form->field($model, 'email') ?>

                <?= $form->field($model, 'password')->passwordInput() ?>

                <div class="form-group">
                    <?= Html::submitButton('Signup', ['class' => 'btn btn-primary', 'name' => 'signup-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>